env:
  browser: true
  es6: true
  node: true
  jest: true

extends:
  - google
  - plugin:react/recommended
  - plugin:eslint-plugin-import/errors
  - plugin:eslint-plugin-import/warnings
  - plugin:eslint-plugin-import/typescript

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

parser: "@typescript-eslint/parser"

parserOptions:
  ecmaVersion: 2021
  sourceType: module

plugins:
  - "@typescript-eslint"

settings:
  react:
    version: detect

rules:
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "^[_]+$"
      argsIgnorePattern: "^[_]+$"
      ignoreRestSiblings: true

  "@typescript-eslint/no-explicit-any":
    - off

  # Needs to disable local no-unused-vars for this rule to work properly
  no-unused-vars:
    - off

  linebreak-style:
    - error
    - unix

  "@typescript-eslint/indent":
    - error
    - 2
    - ignoredNodes:
        - TSTypeParameterInstantiation
      MemberExpression: 1

  # Needs to disable local indent for this rule to work properly
  indent:
    - off

  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: react
          group: external
          position: before
      pathGroupsExcludedImportTypes:
        - react
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true

  import/newline-after-import:
    - error
    - count: 2

  object-curly-spacing: off

  "@typescript-eslint/object-curly-spacing":
    - error
    - never

  semi:
    - off

  "@typescript-eslint/semi":
    - error

  space-in-parens:
    - error
    - never

  require-jsdoc:
    - off

  max-len:
    - 2
    - code: 120
